### ISSUE TITLE
Can ignore Opera Mini...?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/learn-websockets#4]
Can _ignore_ **Opera Mini**...?
Apparently not... http://caniuse.com/usage-table
![caniuse-stats](https://cloud.githubusercontent.com/assets/194400/11025955/a1f0fcb8-869a-11e5-8f5e-774d344fc1fd.png)

More detailed trend: https://www.netmarketshare.com/browser-market-share.aspx?qprid=1&qpcustomb=1
![mobile-stats-opera-mini](https://cloud.githubusercontent.com/assets/194400/11025957/a34837f2-869a-11e5-9cea-298c3a470ca8.png)

> Where are all the Opera Mini users? http://raddevon.com/articles/where-are-opera-mini-users

**Comment by iteles** [comment]
?! I had no idea there were this many people still using it! 😐

**Comment by nelsonic** [comment]
We will _detect_ Opera Mini and encourage people to use a betterer browser. :+1:
